version: "3.8"
name: "dotoo-backend-dev-env"

services:
  postgres:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    restart: no
    environment:
      POSTGRES_DB: dotoodevdb
      POSTGRES_USER: DoTooDevUser
      POSTGRES_PASSWORD: DoTooDevPassword
    volumes:
      - dotoo-dev-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dotoo-dev-postgres-network
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: no
    ports:
      - "8081:8080"
    networks:
      - dotoo-dev-postgres-network
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: no
    volumes:
      - dotoo-dev-redis:/data
    ports:
      - "6379:6379"
    networks:
      - dotoo-dev-redis-network
  redis-insight:
    image: redislabs/redisinsight
    container_name: ${COMPOSE_PROJECT_NAME}-redis-insight
    restart: no
    ports:
      - "8082:8001"
    networks:
      - dotoo-dev-redis-network

volumes:
  dotoo-dev-redis: {}
  dotoo-dev-pgdata: {}

networks:
  dotoo-dev-redis-network:
    name: dotoo-dev-redis-network
  dotoo-dev-postgres-network:
    name: dotoo-dev-postgres-network